@startuml

@startwbs
*[#orange] Department: Online

**[#silver] Division: Ecom.Clients
*** Partners Team
*** Choice Team
*** Marketing Team
*** OMS/CRM Team
*** Purchase Team

**[#silver] Division: Ecom.Operations
*** Payment Team
*** Assembly Team
*** Delovery Team
*** OMS Team

**[#silver] Division: DevOps
*** Ecom Team
*** Core Team
*** Platform Team

**[#silver] Division: Platform
*** Cuscom Team
*** MagnitID Team
*** Search Team
*** UGC Team
*** StocksAndPrices Team
*** AB Team

**[#silver] Direction: Core
*** App Tech Team
*** Web Base Team
***[#tan] Division: Client Needs
**** Acquisition Team
**** Catalog Team
**** Promo Team
**** Online Journal Team
**** Main Screen Team
**** Multiformat Team
**** User Reviews Team
**** Virtual Card Team
***[#tan] Division: Extra Value
**** Promo Games Team
**** Promo Mobile Team

@endwbs
@enduml
