@startuml

@startwbs
*[#orange] Department: Online

**[#silver] Direction: Ecom
*** Выбор Team
*** Покупка Team
*** Маркетинг Team
*** OMS/CRM Team
*** Payment Team
*** Collect Team
*** Delivery Team
*** Courier Team
*** Partners Team

**[#silver] DevOps Team

**[#silver] Division: Platform
*** Middleware Team
*** MagnitID Team
*** Search Team
*** UGC Team

**[#silver] Direction: Core
*** Checkout Team
*** Release Team
*** App Base Team
*** Web Base Team
***[#tan] Division: Client Needs
**** Virtual Card Team
**** Extra Value Team
**** Product Catalog & Promo Team
**** User Reviews Team
**** [ ... ]

@endwbs
@enduml
